"""empty message

Revision ID: 74467d5f268a
Revises: 48996a21327d
Create Date: 2023-05-09 11:53:24.204819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74467d5f268a'
down_revision = '48996a21327d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moon',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moon')
    # ### end Alembic commands ###
